# Generated by Django 4.1.3 on 2022-11-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
